---

- name: create group
  group: name={{ user }} state=present

- name: create user
  user: name={{ user }}
        groups={{ user }}
        shell=/bin/zsh
        state=present

- name: create folders
  file: path={{ user_home }}/{{ item }}
        owner={{ user }}
        group={{ user_group }}
        state=directory
  with_items:
    - opt
    - workspace
    - workspace_book
    - workspace_job
    - workspace_learn
    - workspace_open
