---

- name: update apt cache
  apt: update_cache=yes

- name: install terminator
  apt:
    state: latest
    name: terminator
  tags: terminator

- name: install command-line tools
  apt:
    state: latest
    name: ['zsh', 'git', 'tree', 'screen', 'tmux', 'jq', 'pass']

- name: install python tools
  apt:
    state: latest
    name: ['python3-pip', 'python3-virtualenv']

- name: install ui tools
  apt:
    state: latest
    name: gnome-sushi

- name: install python virtualenv wrapper
  pip:
    state: latest
    name: ['virtualenvwrapper', 'yq']
