---

- name: update apt cache
  apt: update_cache=yes

- name: install tools
  apt: name={{ item }} state=latest
  with_items:
   - python-pip
   - encfs
   - rclone

- name: install aws cli
  pip: name={{ item }} state=latest
  with_items:
    - awscli

- name: create folders
  file: path={{ user_home }}/{{ item }}
        owner={{ user }}
        group={{ user_group }}
        mode=0750
        state=directory
  with_items:
    - encrypted
    - Storage

- name: create empty config file
  file: path={{ user_home }}/{{ item }}
        owner={{ user }}
        group={{ user_group }}
        mode=0600
        state=touch
  with_items:
    - .config/rclone/rclong.conf
    - .aws/credentials


- name: mount encfs
  command: encfs {{ user_home }}/encrypted {{ user_home }}/Storage - --extpass="gpg --no-mdc-warning -o - {{ encfs_gpg_keyfile }}"
