---

- name: update apt cache
  apt: update_cache=yes

- name: install tools
  apt: name={{ item }} state=latest
  with_items:
   - encfs
   - s3fs

- name: create folders
  file: path={{ user_home }}/{{ item }}
        owner={{ user }}
        group={{ user_group }}
        mode=0750
        state=directory
  with_items:
    - encrypted
    - Storage

- name: create empty config file
  file: path={{ user_home }}/{{ item }}
        owner={{ user }}
        group={{ user_group }}
        mode=0600
        state=touch
  with_items:
    - .passwd-s3fs


- name: mount S3 bucket
  command: s3fs {{ s3_bucket }} {{ user_home }}/encrypted -o use_cache=/tmp

- name: mount encfs
  command: encfs {{ user_home }}/encrypted {{ user_home }}/Storage - --extpass="gpg --no-mdc-warning -o - {{ encfs_gpg_keyfile }}"
