---

- name: update apt cache
  apt: update_cache=yes

- name: install encfs and rclone
  apt:
    state: latest
    name:
      - python3-pip
      - encfs
      - rclone

- name: create empty rclone config file
  file: path={{ user_home }}/{{ item }}
        owner={{ user }}
        group={{ user_group }}
        mode=0600
        state=touch
  with_items:
    - .config/rclone/rclone.conf

- name: create encfs folders
  file: path={{ user_home }}/{{ item }}
        owner={{ user }}
        group={{ user_group }}
        mode=0750
        state=directory
  with_items:
    - encrypted
    - Storage

- name: mount encfs folders
  command: encfs {{ user_home }}/encrypted {{ user_home }}/Storage - --extpass="gpg --no-mdc-warning -o - {{ encfs_gpg_keyfile }}"
