---
sudo: required
dist: trusty


before_install:
    - sudo add-apt-repository -y ppa:ansible/ansible
    - sudo apt-get -qq update
    - sudo apt-get install -y ansible


install:
  - ansible --version


script:
  - ./test.sh
