---
sudo: required

before_install:
    - sudo add-apt-repository -y ppa:ansible/ansible
    - sudo apt-get -qq update
    - sudo apt-get install -y ansible


install:
  - ansible --version


script:
  - ansible-playbook --inventory=hosts --connection=local site.yml --tags=vim --syntax-check
  - ansible-playbook --inventory=hosts --connection=local site.yml --tags=vim
