---
sudo: required
dist: focal

before_install:
    - sudo apt-get install -y software-properties-common
    - sudo add-apt-repository -y ppa:ansible/ansible
    - sudo apt-get -qq update
    - sudo apt-get install -y ansible

install:
  - ansible --version

script:
  - ANSIBLE_CONFIG="ALLOW_WORLD_READABLE_TMPFILES=True" ./test.sh
