---
sudo: required
dist: focal

before_install:
    - sudo apt-get install -y software-properties-common
    - sudo add-apt-repository -y ppa:ansible/ansible
    - sudo apt-get -qq update
    - sudo apt-get install -y ansible
    - sudo apt-get install -y acl

install:
  - ansible --version

script:
  - ANSIBLE_CONFIG="allow_world_readable_tmpfiles=True" ./test.sh
