---
sudo: required
dist: trusty


before_install:
    - sudo add-apt-repository -y ppa:ansible/ansible
    - sudo apt-get -qq update
    - sudo apt-get install -y ansible


install:
  - ansible --version


script:
  # test syntax on all roles
  - ansible-playbook --inventory=hosts --connection=local site.yml --syntax-check

  - ansible-playbook --inventory=hosts --connection=local site.yml --tags=setup

  # test tags
  - ansible-playbook --inventory=hosts --connection=local site.yml --tags=vim

  # test roles
  - ansible-playbook --inventory=hosts --connection=local site.yml --tags=devtools
  - ansible-playbook --inventory=hosts --connection=local site.yml --tags=systools
