---
sudo: required

language: python
python: "2.7"


before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y python-pip


install:
  - pip install ansible
  - ansible --version


script:
  - ansible-playbook --inventory=hosts --connection=local site.yml --tags=vim --syntax-check
  - ansible-playbook --inventory=hosts --connection=local site.yml --tags=vim
