---

- hosts: default
  remote_user: vagrant
  become: yes

  tasks:
    - name: install python3 packages
      apt:
        name:
          - python3
          - python3-pip
        update_cache: yes
        state: latest

    - name: install ansible with pip3
      command: pip3 install ansible
