---

- name: install packages required by docker
  apt:
    update_cache: yes
    state: latest
    name: ['apt-transport-https', 'ca-certificates', 'software-properties-common']
  tags: docker

- name: add key for docker repo
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags: docker

- name: add docker repo
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu  {{ ansible_distribution_release }} stable'
    state: present
  tags: docker

- name: install docker
  apt: name=docker-ce update_cache=yes state=latest
  tags: docker

- name: add user to docker group
  user: name={{ user }}
        groups=docker
        append=yes
  tags: docker

- name: start docker
  service: name=docker state=started enabled=yes
  tags: docker

- name: test docker
  command: "docker run hello-world"
  tags: docker
