---

- name: install docker packages
  apt: name={{ item }} state=latest
  with_items:
   - docker.io
  tags: docker

- name: create docker group
  group: name=docker state=present
  tags: docker

- name: add user to docker group
  user: name={{ user }}
        groups=docker
        append=yes
  tags: docker

- name: start docker
  service: name=docker state=started enabled=yes
  tags: docker

- name: test docker
  command: "docker run hello-world"
  tags: docker


- name: install virtualbox
  apt: name={{ item }} state=latest
  with_items:
   - virtualbox-qt
  tags: vagrant

- name: download vagrant latest
  get_url: url="http://releases.hashicorp.com/vagrant/{{ vagrant_version }}/vagrant_{{ vagrant_version }}_x86_64.deb" dest=/tmp
  when: ansible_distribution == "Ubuntu"
  tags: vagrant

- name: install vagrant latest deb
  apt: deb=/tmp/vagrant_{{ vagrant_version }}_x86_64.deb
  when: ansible_distribution == "Ubuntu"
  tags: vagrant

# testing it on a vagrant box does not work
- name: download ubuntu 14.04 vagrant box
  command: "vagrant box add ubuntu/trusty64"
  when: ansible_virtualization_type != "virtualbox"
  tags: vagrant
