---

- name: install system tools
  apt: name={{ item }} state=present
  with_items:
   - htop
   - iotop
   - inotify-tools
   - sysstat
   - sysdig
   - oprofile
   - nicstat
   - iptraf
   - pax-utils

- name: install kernel tools
  apt: name={{ item }} state=present
  with_items:
   - linux-tools-generic
   - linux-cloud-tools-generic
  tags: perf

- name: install systemtap
  apt: name={{ item }} state=present
  with_items:
   - systemtap
  tags: systemtap

- name: test systemtap
  command: stap -v -e 'probe vfs.read {printf("read performed\n"); exit()}'
  tags: systemtap
