---

- name: install aws cli
  pip: name=awscli state=latest

- name: create .aws
  file: path={{ user_home }}/{{ item }}
        owner={{ user }}
        group={{ user_group }}
        mode=0750
        state=directory
  with_items:
    - .aws

- name: create empty aws config files
  file: path={{ user_home }}/.aws/{{ item }}
        owner={{ user }}
        group={{ user_group }}
        mode=0600
        state=touch
  with_items:
    - credentials
