---

- name: install git repo cleaner bfg, https://rtyley.github.io/bfg-repo-cleaner/
  get_url: url='https://search.maven.org/remote_content?g=com.madgag&a=bfg&v=LATEST' dest={{ bfg_home }}/{{ bfg_jar }}
  tags: bfg

- name: change access to bfg jar file
  file: path={{ bfg_home }}/{{ bfg_jar }} owner={{ user }} group={{ user }} mode=0440 state=file
  tags: bfg
