---

- name: install dev tool packages
  apt:
    update_cache: yes
    state: latest
    name: ['git', 'meld', 'ack', 'xclip', 'jq', 'cloc']


- name: install vim
  include: vim.yml
  tags: vim

- name: install neovim
  include: neovim.yml
  tags: neovim

- name: install vscode
  include: vscode.yml
  tags: vscode

- name: install swagger
  include: swagger.yml
  when: False

- name: install git repo cleaner
  include: git_repo_cleaner.yml
  when: False
