---

- name: install dev tools
  apt:
    update_cache: yes
    state: latest
    name: ['git', 'meld']

- name: install C-dev
  apt:
    state: latest
    name: ['build-essential', 'cmake', 'valgrind', 'kcachegrind']


- name: install vim
  include: "vim.yml"

- name: install swagger
  include: "swagger.yml"

- name: install git repo cleaner
  include: "git_repo_cleaner.yml"
