---

- name: install dev tools
  apt:
    update_cache: yes
    state: latest
    name: ['git', 'meld', 'ack', 'jq']


- name: install vim
  include: vim.yml

- name: install swagger
  include: swagger.yml

- name: install git repo cleaner
  include: git_repo_cleaner.yml
