---

- name: install dev tools
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
   - build-essential
   - vim-gnome
   - git
   - gitg
   - meld
   - valgrind
   - kcachegrind


- name: install nodejs
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
   - nodejs
   - npm
  tags: swagger

- name: npm requires node in the path
  file: src=/usr/bin/nodejs dest=/usr/bin/node state=link
  tags: swagger

- name: clone swagger editor
  git: repo=https://github.com/swagger-api/swagger-editor.git dest={{ user_home }}/swagger-editor
  become_user: "{{ user }}"
  become_method: sudo
  tags: swagger


- name: install git repo cleaner bfg, https://rtyley.github.io/bfg-repo-cleaner/
  get_url: url='https://search.maven.org/remote_content?g=com.madgag&a=bfg&v=LATEST' dest={{ bfg_home }}/{{ bfg_jar }}
  tags: bfg

- name: change access to bfg jar file
  file: path={{ bfg_home }}/{{ bfg_jar }} owner={{ user }} group={{ user }} mode=0440 state=file
  tags: bfg
