---

- name: update apt cache
  apt:
    update_cache: yes


- name: install packages required by vscode
  apt:
    state: latest
    name: ['apt-transport-https', 'software-properties-common']

- name: add key for vscode repo
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: add vscode repo
  apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
    state: present

- name: install vscode
  apt:
    name: code
    update_cache: yes
    state: latest


- name: install neovim
  apt:
    name: neovim
    state: latest

- name: create neovim autoload dir
  file:
    path: "{{ neovim_stdpath_data }}/site/autoload"
    state: directory

- name: install Plug
  get_url:
    url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    dest: "{{ neovim_stdpath_data }}/site/autoload/plug.vim"

- name: copy init.vim
  copy:
    src: ./files/init.vim
    dest: "{{ neovim_stdpath_config }}/init.vim"
