---

- name: install oracle jdk
  include: oracle_java.yml
  tags: oracle-java

- name: install openjdk
  include: openjdk.yml
  tags: openjdk

- name: install maven
  include: maven.yml
  tags: maven31

- name: install scala
  include: scala.yml
