---

- name: install tools
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
   - software-properties-common
   - debconf-utils
  tags: oracle-java

- name: add oracle java repo
  apt_repository: repo='ppa:webupd8team/java' state=present
  tags: oracle-java

- name: accept oracle license
  command: echo "oracle-java{{ item }}-installer shared/accepted-oracle-license-v1-1 select true" | sudo debconf-set-selections
  with_items:
    - 7
    - 8
  tags: oracle-java

- name: install java, jre and jdk
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
   - oracle-java7-installer
   - oracle-java8-installer
  tags: oracle-java


- name: install openjdk 7
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
   - openjdk-7-jdk
  tags: openjdk

- name: install openjdk 8
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
   - openjdk-8-jdk
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int >= 16
  tags: openjdk


- name: install maven
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
   - maven

- name: download maven 3.1
  get_url:
    url=http://archive.apache.org/dist/maven/maven-3/3.1.1/binaries/apache-maven-3.1.1-bin.tar.gz
    dest=/usr/local/apache-maven-3.1.1-bin.tar.gz
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int <= 14
  tags: maven31

- name: install maven 3.1
  unarchive:
    src=/usr/local/apache-maven-3.1.1-bin.tar.gz
    dest=/usr/local/
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int <= 14
  tags: maven31

- name: create sym link to maven 3.1
  file: src=/usr/local/apache-maven-3.1.1 dest=/usr/local/apache-maven-3.1 state=link
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int <= 14
  tags: maven31


- name: add repo for sbt
  shell: echo 'deb https://dl.bintray.com/sbt/debian /' | tee -a /etc/apt/sources.list.d/sbt.list creates=/etc/apt/sources.list.d/sbt.list
  tags: sbt

- name: add key for sbt repo
  apt_key: keyserver=keyserver.ubuntu.com id=642AC823 state=present
  tags: sbt

- name: install sbt package
  apt: name=sbt update_cache=yes state=present
  tags: sbt
