---

- name: install openjdk 7
  apt:
    name: openjdk-7-jdk
    update_cache: yes
    state: latest
  when: ansible_distribution == "Ubuntu"
    and ansible_distribution_major_version|int < 16

- name: install openjdk 8
  apt:
    name: openjdk-8-jdk
    update_cache: yes
    state: latest
  when: ansible_distribution == "Ubuntu"
    and ansible_distribution_major_version|int >= 16

- name: install openjdk 11
  apt:
    name: openjdk-11-jdk
    update_cache: yes
    state: latest
  when: ansible_distribution == "Ubuntu"
    and ansible_distribution_major_version|int >= 18

- debug:
    msg: 'run (update-alternatives --config java) to change the java version.'
