---

- name: install python3 linux packages
  apt:
    state: latest
    name:
      - python3
      - python3-pip
      - python3-dev
      - python3-venv

- name: install alternative for python3
  alternatives:
    name: python
    link: /usr/bin/python
    path: /usr/bin/python3
    priority: 3

- name: reset python alternatives to auto
  command: update-alternatives --auto python

- name: read python version
  command: python --version
  register: python_version

- debug:
    msg: "(python --version) is {{ python_version.stdout }}"
